CREATE DATABASE supportchat;

USE supportchat;

CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100),
 password VARCHAR(100)
);

CREATE TABLE messages(
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100),
 message TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);